version: "3.5"

services:
  mongo:
    image: mongo:4.2.6
    container_name: mongo
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment: 
      MONGO_INIT_DATABASE: frank
    networks:
      franknet:
        ipv4_address: 172.20.0.5
 
  # container that only initializes and seeds 
  # the mongodb container with FRANK data and then exits
  mongo-seed:
    container_name: mongo-seed
    build: .
    image: mongo-seed:1.0
    networks:
      franknet:
        ipv4_address: 172.20.0.6
    depends_on:
      - mongo
  
  # redis db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      franknet:
        ipv4_address: 172.20.0.7

  # neo4j
  neo4j:
    container_name: neo4j
    image: neo4j:4.0.1
    restart: always
    environment:
      NEO4J_AUTH: neo4j/@neo4j123
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687      
      NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
    volumes:
      - neo4j_data:/data
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      franknet:
        ipv4_address: 172.20.0.8

  
  # frank api
  frank-api:
    container_name: frank-api
    build:
      context: ../franky
      dockerfile: ./setup/docker/Dockerfile
    image: frank-api:1.0
    restart: always
    volumes: 
      - ../franky/src:/app
      - ../franky/logs/nginx:/var/log/nginx 
      - ../franky/logs/uwsgi:/app/logs/uwsgi
    ports:
      - 9876:80
      - 9877:443
    networks:
      franknet:
        ipv4_address: 172.20.0.3
    depends_on:
      - mongo
      - redis
      - neo4j      


  # frank-ui
  frank-ui:
    container_name: frank-ui
    build:
      context: ../frank-ui
      dockerfile: ./setup/docker/Dockerfile
    image: frank-ui:1.0
    restart: always
    volumes:
      - ../frank-ui/src:/app/src
      - ../frank-ui/logs/nginx_ui:/var/log/nginx
    networks:
      franknet:
        ipv4_address: 172.20.0.2
    ports: 
      - 9080:80
  
volumes:
  neo4j_data:
  mongodb_data:

networks:
  franknet:
    name: franknet
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.20.0.0/24
